' VSCode Extensions required: "jebbs.plantuml" and "Mebrahtom.plantumlpreviewer"

@startuml THShop

title THShop Tables

' set flow direction from left to right
left to right direction

' keywords
!define PK <color:red>PK</color>
!define FK <color:orange>FK</color>

' file types
!define VARCHAR(x) <color:green>VARCHAR[x]</color>
!define INT <color:blue>INT</color>
!define BIT <color:SkyBlue>BIT</color>
!define DOUBLE <color:LightBlue>DOUBLE</color>
!define TIMESTAMP <color:brown>TIMESTAMP</color>

' Entities

map users {
  userID => PK INT
  email => VARCHAR(30)
  password => VARCHAR(30)
  salt => VARCHAR(30)
  firstname => VARCHAR(30)
  lastname => VARCHAR(30)
  country => VARCHAR(30)
  city => VARCHAR(30)
  zipcode => VARCHAR(30)
  street => VARCHAR(30)
  phone => VARCHAR(30)
  birthday => TIMESTAMP
  created => TIMESTAMP
}

map views {
  userID => PK FK INT
  itemID => PK FK INT
  count => INT
  date => TIMESTAMP
}

map carts {
  userID => PK FK INT
  itemID => PK FK INT
  quantity => INT
}

map items {
  itemID => PK INT
  dealerID => FK INT
  name => VARCHAR(30)
  description => VARCHAR(50)
  price => DOUBLE
  inStock => BIT
  manufacturer => VARCHAR(30)
  dateAdded => TIMESTAMP
}

map dealers {
  dealerID => PK INT
  name => VARCHAR(30)
}

map orders {
  orderID => PK INT
  userID => FK INT
  status => VARCHAR(10)
  paymentMethod => VARCHAR(10)
  created => TIMESTAMP
}

map orderItems {
  orderID => PK FK INT
  itemID => PK FK INT
  quantity => INT
}

map roles {
  userID => PK INT
  permissionID => PK INT
  isDefault => BIT
}

map permissions {
  permissionID => PK INT
  name => VARCHAR(30)
  description => VARCHAR(30)
}

map tokens {
  tokenID => PK INT
  userID => FK INT
  jwt => VARCHAR(30)
  refreshToken => VARCHAR(30)
  validDurationInHours => INT 
  validUntil => TIMESTAMP
  created => TIMESTAMP
  lastLogin => TIMESTAMP
}


' Associations 

users::userID "1" -- "n" roles::userID
roles::permissionID "n" -- "1" permissions::permissionID

users::userID "1" -- "n" tokens::userID

users::userID "1" -- "n" carts::userID
carts::itemID "n" --- "1" items::itemID

users::userID "1" -- "n" views::userID
views::itemID "n" -- "1" items::itemID

' items::dealerID "n" -- "1" dealers::dealerID
users::userID "1" -- "n" orders::userID
dealers::dealerID "1" -- "n" items::dealerID

orders::orderID "1" -- "n" orderItems::orderID
orderItems::itemID "n" -- "1" items::itemID


@enduml