' VSCode Extensions required: "jebbs.plantuml" and "Mebrahtom.plantumlpreviewer"

@startuml THShop

title THShop Tables

' set flow direction from left to right
left to right direction

' keywords
!define PK <color:red>PK</color>
!define FK <color:orange>FK</color>

' file types
!define VARCHAR(x) <color:green>VARCHAR[x]</color>
!define INT <color:blue>INT</color>
!define TINYINT <color:SkyBlue>TINYINT</color>
!define DOUBLE <color:LightBlue>DOUBLE</color>
!define TIMESTAMP <color:brown>TIMESTAMP</color>
!define DATETIME <color:DarkGray>DATETIME</color>

' Entities

map users {
  userID => PK INT
  active => TINYINT
  email => VARCHAR(30)
  password => VARCHAR(30)
  salt => VARCHAR(30)
  firstname => VARCHAR(30)
  lastname => VARCHAR(30)
  phone => VARCHAR(30)
  phoneAlt => VARCHAR(30)
  gender => VARCHAR(1)
  birthday => DATETIME
  created => TIMESTAMP
  lastLogin => TIMESTAMP
}

map items {
  itemID => PK INT
  dealerID => FK INT
  name => VARCHAR(30)
  description => VARCHAR(50)
  price => DOUBLE
  inStock => TINYINT
  manufacturer => VARCHAR(30)
  dateAdded => TIMESTAMP
}

map roles {
  userID => PK FK INT
  permissionID => PK FK INT
  isDefault => TINYINT
}

map permissions {
  permissionID => PK INT
  name => VARCHAR(30)
  description => VARCHAR(30)
}

map views {
  userID => PK FK INT
  itemID => PK FK INT
  count => INT
  date => TIMESTAMP
}

map orders {
  orderID => PK INT
  userID => FK INT
  status => VARCHAR(10)
  paymentMethod => VARCHAR(10)
  created => TIMESTAMP
}

map itemDetails {
  itemDetailsID => PK INT
  itemID => FK INT
  orderID => FK INT
  quantity => INT
  color => VARCHAR(10)
  size => VARCHAR(10)
}

map carts {
  userID => PK FK INT
  itemDetailsID => PK FK INT
}

map addressTypes {
  userID => PK FK INT
  addressID => PK FK INT
  isBillingAddress => TINYINT
  isDeliveryAddress => TINYINT
}

map addresses {
  addressID => PK INT
  country => VARCHAR(2)
  city => VARCHAR(30)
  zipcode => VARCHAR(8)
  street => VARCHAR(30)
}

map dealers {
  dealerID => PK INT
  addressID => FK INT
  name => VARCHAR(30)
}


' Associations 

users::userID "1" -- "n" addressTypes::userID
addressTypes::addressID "n" -- "1" addresses::addressID

addressTypes::userID -- users::userID
addresses::addressID -- addressTypes::addressID

users::userID "1" -- "n" roles::userID
roles::permissionID "n" -- "1" permissions::permissionID

orders::orderID "1" -- "n" itemDetails::orderID

users::userID "1" -- "n" views::userID
views::itemID "n" -- "1" items::itemID

users::userID "1" -- "n" orders::userID
dealers::dealerID "1" -- "n" items::dealerID
addresses::addressID "1" -- "1" dealers::addressID

carts::itemDetailsID "n" -- "1" itemDetails::itemDetailsID
itemDetails::itemID "1" -- "1" items::itemID

users::userID "1" --- "n" carts::userID

@enduml